### ISSUE TITLE
toml config ignored

### ISSUE THREAD

**Issue by gennaro-tedesco** [Macchina-CLI/macchina#97] opened 2021-05-18 23:19 UTC
**Describe the bug**
`macchina.toml` settings are being ignored

**To Reproduce**
```
export XDG_CONFIG_HOME="$HOME/.config"
cd $XDG_CONFIG_HOME && mkdir macchina && cd macchina
wget macchina.toml https://raw.githubusercontent.com/Macchina-CLI/macchina/main/macchina.toml
```
I have restarted the terminal, re-sourced my shell configurations and so forth, but no changes occur. Must one specify explicitly that `macchina` must be reading the config via a flag or so?

**Expected behavior**
The configuration `.toml` changes the appearence of `macchina`.

**System Information**

<img width="603" alt="Screenshot 2021-05-19 at 01 19 00" src="https://user-images.githubusercontent.com/15387611/118735203-374ad180-b840-11eb-8473-5c91d34e15f0.png">

**Comment by uttarayan21** [comment] 2021-05-19 05:43
We are using [dirs-rs](https://github.com/dirs-dev/dirs-rs) to get the config directory.
According to that in macos config_dir is in `// Mac: Some(/Users/Alice/Library/Application Support)`.
So you probably will have to place it in there.

**Comment by gennaro-tedesco** [comment] 2021-05-19 08:47
I have tried the specifications indicated in `dirs-rs`, nevertheless the configuration is still ignored; not a big problem, I am just going to alias the options to the command instead.

Perhaps it can be useful, down the road, to expose to the user an environment variable or a flag through which they can point to whichever location they choose, something along the lines of
```
export $MACCHINA_PATH=/my/custom/config/path
```
that they can place in their shell profile or so.

**Comment by uttarayan21** [comment] 2021-05-19 11:03
Thank you for the suggestion.
I have added a `--config` flag as well as `MACCHINA_CONF` environment variable both of which can set the config file.

**Comment by gennaro-tedesco** [comment] 2021-05-19 11:36
Woow, thank you for your quick effort! I guess you are referring to https://github.com/Macchina-CLI/macchina/pull/98.

Thank you again and keep up the awesome `macchina`!

**Comment by gennaro-tedesco** [comment] 2021-05-25 11:16
Sorry to re-comment on a closed issue: I saw that a [new release](https://github.com/Macchina-CLI/macchina/releases/tag/v0.8.21) was issued: is this already available via `brew` or must we compile the binaries (upgrading it seems the latest is still 0.8.1)?

**Comment by grtcdr** [comment] 2021-05-25 13:51
> Sorry to re-comment on a closed issue: I saw that a [new release](https://github.com/Macchina-CLI/macchina/releases/tag/v0.8.21) was issued: is this already available via `brew` or must we compile the binaries (upgrading it seems the latest is still 0.8.1)?

It still isn't available on `brew`, see #100

**Comment by grtcdr** [comment] 2021-05-26 20:53
Hey @gennaro-tedesco, version 0.8.21 should be out on homebrew. :)

**Comment by gennaro-tedesco** [comment] 2021-05-27 08:21
Awesome, I have installed it and confirm the changes with the `$MACCHINA_CONF` work as intended!

**Comment by gennaro-tedesco** [comment] 2021-11-30 20:54
`.toml` configuration ignored again with latest releases - same settings as per original post.

**Comment by grtcdr** [comment] 2021-11-30 23:34
I'll have a look at it, sorry this happened (again).

**Comment by gennaro-tedesco** [comment] 2021-12-09 09:33
Any progress on this by any chance?

**Comment by grtcdr** [comment] 2021-12-09 09:59
I'm in the middle of refactoring the way configurations are handled, the progress is happening on the [v6](https://github.com/Macchina-CLI/macchina/pull/200) branch. Due to the new architectural changes that macchina has undergone with the separation of themes from the main config, `MACCHINA_CONF` will become `MACCHINA_DIR` to accomodate for the usage of themes by specifying an entire directory.

**Comment by gennaro-tedesco** [comment] 2021-12-16 01:10
I have seen that v6 has been released and I have updated it: 
```
$ macchina -v
macchina     6.0.1
libmacchina  4.0.2
```
As explained [here](https://github.com/Macchina-CLI/macchina#customization) I moved the configuration to the new one, making use of themes in a separate folder as indicated. However, `macchina` again does not detect them: see screenshot below:
<img width="801" alt="Screenshot 2021-12-16 at 02 07 38" src="https://user-images.githubusercontent.com/15387611/146289250-53c172b7-cbb2-4e96-9eb2-b90e016e4615.png">
```
ls ~/.config/macchina/themes
Permissions Size User           Date Modified Name
.rw-r--r--   966 gennarotedesco 16 Dec 01:53  Helium.toml
.rw-r--r--   966 gennarotedesco 16 Dec 01:53  Hydrogen.toml
```
the themes are there, I have copied and pasted the documentation examples without changing anything. Still, I am unable to get it to work.

At this point I would ask if there is a plan to really test it on macOS and make it work: I am trying really hard to use it but I am spending more time looking at these GitHub issues than ever actually using the tool.

**Comment by grtcdr** [comment] 2021-12-16 01:22
>  I am trying really hard to use it but I am spending more time looking at these GitHub issues than ever actually using the tool.

I get your frustration, and I'm really sorry you're having all this trouble :(

> At this point I would ask if there is a plan to really test it on macOS and make it work

I unfortunately don't have the hardware, or time to maintain a wide variety of operating systems, all of which have their own fair share of weird quirks. I can however try to help you to the best of my ability :)

@123marvin123 is the primary contributor to the macOS side of things and his schedule is pretty tight, so I'm all you got.

Anyways, can you please post the two themes?

**Comment by gennaro-tedesco** [comment] 2021-12-16 01:45
The themes are the ones shown [here](https://github.com/Macchina-CLI/macchina/tree/main/contrib/themes) and the [macchina.toml](https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.toml) is the same as in the link, only obviously having `theme = "Helium/Hydrogen"` accordingly.

I have tried with "bare themes" too, namely making a minimal theme with 1-2 lines just to see if the configuration is read, and they do not work either, so I suspect the `macchina.toml` does not see the reference to the `macchina/themes` folder?

**Comment by grtcdr** [comment] 2021-12-16 02:00
> I suspect the `macchina.toml` does not see the reference to the `macchina/themes` folder?

This is probably the case, although I'm having a hard time tracking such a bug down, especially since I've carefully tweaked the configuration paths in **v6** to look at the correct paths depending on the operating system, and macOS being the only OS suffering from this doesn't help. I'll look even _harder_, there's got to be a way.

**Comment by 123marvin123** [comment] 2021-12-16 09:16
I will look at this issue today and push a solution for macOS.

**Comment by grtcdr** [comment] 2021-12-16 10:16
> I will look at this issue today and push a solution for macOS.

Can you work on this in the v6.0.2 branch?

**Comment by 123marvin123** [comment] 2021-12-16 20:33
Please also see #239. There seems to be an issue with the Helium theme which silently fails. Also, the `dirs` crate does not respect $XDG_CONFIG_HOME, the default location for the macchina.toml file is under /Users/YOU/.config/macchina/macchina.toml, alternatively you can provide the config via the --config flag.

**Comment by gennaro-tedesco** [comment] 2021-12-16 21:29
https://github.com/Macchina-CLI/macchina/issues/239 is about the Hydrogen theme, not Helium, is it not? From the screenshot above (see my previous comment) one can see that the location of my configuration is indeed `/Users/YOU/.config/macchina` (with `macchina.toml` and `/themes` in there) - so I would say the paths are correct.

Do we want to create a minimally reproducible `curl` example to execute and try, say something along the lines of 
```
brew install macchina
curl .../macchina.toml
curl .../macchina/themes
```
so that we make sure that we both reproduce the same?

**Comment by 123marvin123** [comment] 2021-12-16 21:40
> #239 is about the Hydrogen theme, not Helium, is it not? From the screenshot above (see my previous comment) one can see that the location of my configuration is indeed `/Users/YOU/.config/macchina` (with `macchina.toml` and `/themes` in there) - so I would say the paths are correct.
> 
> Do we want to create a minimally reproducible `curl` example to execute and try, say something along the lines of
> 
> ```
> brew install macchina
> curl .../macchina.toml
> curl .../macchina/themes
> ```
> 
> so that we make sure that we both reproduce the same?

Oh, you're right, it's about the Hydrogen theme, sorry. We can create a reproducible example, please keep in mind that the changes that I made today are not (yet) in Homebrew. I created a new branch in the repository to keep track of our minimally reproducible example:

```bash
brew install macchina
cd ~/.config
mkdir macchina && cd macchina
curl https://raw.githubusercontent.com/Macchina-CLI/macchina/issue-97-example/contrib/macchina.toml > macchina.toml
mkdir themes && cd themes
curl https://raw.githubusercontent.com/Macchina-CLI/macchina/issue-97-example/contrib/themes/Lithium.toml > Lithium.toml
```

But even for the old version (6.0.1), this returns the proper output with the correct theme (for me):
<img width="472" alt="CleanShot 2021-12-16 at 22 38 04@2x" src="https://user-images.githubusercontent.com/7266447/146452856-18b1e771-9eb5-4ed2-8d0a-c0e2533257df.png">

There is a bug in 6.0.1 that will always print an error message if there is no default config file found:
<img width="691" alt="CleanShot 2021-12-16 at 22 39 03@2x" src="https://user-images.githubusercontent.com/7266447/146452952-e686fc63-f1db-4685-96ac-747ad58c9374.png">

But that's fixed in 6.0.2. Can you try the example above?

**Comment by gennaro-tedesco** [comment] 2021-12-16 22:36
Amazingly enough it seems that the line that breaks the code is:
```
palette         = "Light"
```
in the theme definition. 

Your example works fine; I was curious and I tried with other themes, like Hydrogen and Helium - and they still broke. So I commented out one line at a time (monkey debugging method 😝 ) and saw that if yo remove `palette = ...` from any theme they work just fine. Likewise, if you _add_ it to your example, it breaks again as well.

**Comment by grtcdr** [comment] 2021-12-17 10:36
Well that's a good ending :)

I'm sorry I wasn't able to catch this before the release of v6, but I'm glad you figured it out.

I'll have that fixed ASAP.

**Comment by 123marvin123** [comment] 2021-12-17 14:35
> Amazingly enough it seems that the line that breaks the code is:
> 
> ```
> palette         = "Light"
> ```
> 
> in the theme definition.
> 
> Your example works fine; I was curious and I tried with other themes, like Hydrogen and Helium - and they still broke. So I commented out one line at a time (monkey debugging method 😝 ) and saw that if yo remove `palette = ...` from any theme they work just fine. Likewise, if you _add_ it to your example, it breaks again as well.
> 
> Can you confirm this is the case for you as well? See below for demo:
> 
>  Screen.Recording.2021-12-16.at.23.38.58.mov 
> 
> Now the Lithium theme does have its own palette section in the `.toml`, however the same behaviour happens with Hydrogen and Helium (namely removing `palette = ...` makes all work fine).

Yes, it happens with all themes, since `palette = ...` is actually not correct syntax anymore. So when macchina tries to read the theme file, it fails. It's really necessary that we print an error message to inform the user in that case.

**Comment by grtcdr** [comment] 2021-12-17 14:41
Hydrogen is the only offender, all other themes use the latest format.

**Comment by grtcdr** [comment] 2021-12-17 14:44
One question though, is Homebrew packaging the manpages?

**Comment by gennaro-tedesco** [comment] 2022-01-04 08:49
Sorry guys, release to v6.0.3 two days ago changed it again? :p 

Probably time for me to let go of this unrequited love 😭

**Comment by grtcdr** [comment] 2022-01-04 10:17
Changed what?

**Comment by gennaro-tedesco** [comment] 2022-01-04 13:54
The `.toml` configuration is ignored again: I do not get exceptions/errors whilst invoking `macchina`, however the settings are not being parsed.

**Comment by grtcdr** [comment] 2022-01-04 14:15
![image](https://user-images.githubusercontent.com/35816711/148072056-b64af1a2-cc61-4ee8-af2f-db8dad13958f.png)

**Comment by grtcdr** [comment] 2022-01-04 14:24
I think I know what's going on, please bear with me.

**Comment by grtcdr** [comment] 2022-01-04 14:42
I made a slight modification, and it seems to be working on my machine through the manual path that is $HOME/.config/macchina/macchina.toml and not $XDG_CONFIG_HOME/.config/macchina/macchina.toml.

**Comment by gennaro-tedesco** [comment] 2022-01-05 11:10
In my case `$XDG_CONFIG_HOME` is not set either, and the path is the correct one to `$HOME/.config`. Do the themes still live in `$HOME/.config/macchina/themes` (I remember previously we had a problem in the path to the theme not being recognised, and I thought this may still be the case??)?

**Comment by grtcdr** [comment] 2022-01-05 13:20
> I remember previously we had a problem in the path to the theme not being recognised, and I thought this may still be the case??

No, but I found the culprit.

**Comment by grtcdr** [comment] 2022-01-05 13:35
There shouldn't be any more issues now.

**Comment by grtcdr** [comment] 2022-01-09 02:38
How are things looking now, @gennaro-tedesco ?

**Comment by gennaro-tedesco** [comment] 2022-01-09 11:05
Updating to 
```
macchina --version
macchina     6.0.5
libmacchina  6.0.0
```
all seems restored and fine again, I have tried with different configurations and all work well!

**Comment by grtcdr** [comment] 2022-01-09 12:28
Thanks for bearing with me, and sorry about all this.

**Closed** 2022-01-09 12:32 UTC
