### ISSUE TITLE
[BUG] panic on an old mac 

### ISSUE THREAD

**Issue by fdncred** [Macchina-CLI/macchina#73] opened 2021-04-17 15:00 UTC
**Describe the bug**
```
> macchina
thread 'main' panicked at 'No entry found for key 0x7fe6c5600ba0', /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/core-foundation-0.9.1/src/dictionary.rs:233:43
stack backtrace:
   0:        0x1080a8d29 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34f76b2ca42fab41
   1:        0x108080fad - core::fmt::write::h8f13d857463c51c1
   2:        0x1080a8476 - std::io::Write::write_fmt::h0a6214ccb1a8468b
   3:        0x1080a7ba4 - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
   4:        0x1080cb54a - std::panicking::begin_panic_handler::{{closure}}::h99569328be4adae9
   5:        0x1080cb4b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a7e5cc6475b496b
   6:        0x1080cb460 - _rust_begin_unwind
   7:        0x1080cb42f - std::panicking::begin_panic_fmt::hc364d6defd6a88b8
   8:        0x108095862 - core_foundation::dictionary::CFMutableDictionary<K,V>::get::{{closure}}::h1ef14b3201e41ad6
   9:        0x108026032 - macchina::data::get_all_readouts::h822a64d8592cec98
  10:        0x1080281dc - macchina::main::hbb20e545ea1f7921
  11:        0x10800a84a - std::sys_common::backtrace::__rust_begin_short_backtrace::h41354b2dac9becba
  12:        0x10800ac46 - std::rt::lang_start::{{closure}}::hb43fe7bf99502281
  13:        0x108033dfb - _main
```

**To Reproduce**
1. cargo install macchina
2. macchina

**Expected behavior**
not panic

**Screenshots**

**`macchina --doctor` output**
```
macchina --doctor
thread 'main' panicked at 'No entry found for key 0x7f800a501240', /Users/fdncred/.cargo/registry/src/github.com-1ecc6299db9ec823/core-foundation-0.9.1/src/dictionary.rs:233:43
stack backtrace:
   0:        0x10ff35d29 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34f76b2ca42fab41
   1:        0x10ff0dfad - core::fmt::write::h8f13d857463c51c1
   2:        0x10ff35476 - std::io::Write::write_fmt::h0a6214ccb1a8468b
   3:        0x10ff34ba4 - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
   4:        0x10ff5854a - std::panicking::begin_panic_handler::{{closure}}::h99569328be4adae9
   5:        0x10ff584b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a7e5cc6475b496b
   6:        0x10ff58460 - _rust_begin_unwind
   7:        0x10ff5842f - std::panicking::begin_panic_fmt::hc364d6defd6a88b8
   8:        0x10ff22862 - core_foundation::dictionary::CFMutableDictionary<K,V>::get::{{closure}}::h1ef14b3201e41ad6
   9:        0x10feb3032 - macchina::data::get_all_readouts::h822a64d8592cec98
  10:        0x10feb51dc - macchina::main::hbb20e545ea1f7921
  11:        0x10fe9784a - std::sys_common::backtrace::__rust_begin_short_backtrace::h41354b2dac9becba
  12:        0x10fe97c46 - std::rt::lang_start::{{closure}}::hb43fe7bf99502281
  13:        0x10fec0dfb - _main
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Desktop Environment : Aqua
 - Operating System: macOS High Sierra 10.13.6
 - Terminal : iterm2
 - Macchina's version: 0.6.9

**Comment by grtcdr** [comment] 2021-04-17 15:09
Thanks for reporting this, this is a libmacchina issue.

It's not clear to me whether our implementation is lacking is at fault for this panic or there's a bug within core-foundation. @123marvin123 should be able to provide you with more information regarding this bug.

**Comment by fdncred** [comment] 2021-04-17 18:47
It's a MacBook Pro 15"

**Comment by grtcdr** [comment] 2021-04-17 19:08
> It's a MacBook Pro 15"

We're looking into this :)

**Comment by grtcdr** [comment] 2021-04-18 19:18
@fdncred You mentioned it was an old MacBook, did you replace the battery?
We're thinking this is the reason we can't fetch your battery statistics.

**Comment by fdncred** [comment] 2021-04-18 20:27
Interesting. Yes, I replaced the battery long ago.

**Comment by 123marvin123** [comment] 2021-04-18 20:34
Is it an original Apple battery or a third-party replacement? I think the problem is that there is no information about the battery in apples internal system, so macchina fails to query the needed information.

When you execute macchina and it crashes, are you plugged in into wall power or are you using battery power?

**Comment by fdncred** [comment] 2021-04-19 13:52
It's a 3rd party battery that I bought off Amazon and installed myself. What you're saying makes sense, other than having an unhandled exception.

It fails on battery or power. It makes no difference.

**Comment by grtcdr** [comment] 2021-04-20 18:28
Hey there!

We have fixed this and it'll be available in the next release :)

**Comment by fdncred** [comment] 2021-04-20 23:39
Great! Is there any ETA on that release?

**Comment by grtcdr** [comment] 2021-04-21 00:01
> Great! Is there any ETA on that release?

It should be out as soon as #78 is merged!

**Closed** 2021-04-21 03:10 UTC
Labels: bug, fixed

**Comment by fdncred** [comment] 2021-04-21 12:39
No worries. I'll have to give this a try later this evening. Appreciate the help!

**Comment by grtcdr** [comment] 2021-04-21 20:45
> No worries. I'll have to give this a try later this evening. Appreciate the help!

Hey, how are you doing?

Just came to tell you that the new release is out :smiley:

**Comment by fdncred** [comment] 2021-04-21 22:06
Looks like it's working. Thanks again!
