### ISSUE TITLE
[Feature request] Display storage informations with --bars

### ISSUE THREAD

**Issue by eoli3n** [Macchina-CLI/macchina#104] opened 2021-06-16 20:36 UTC
It would be great to be able to configure macchina to show one or more bar about a filesystem.
I use ZFS, so it would be even greater to be able to show zpool or a dataset usage.

![macchina](https://user-images.githubusercontent.com/14223657/122289489-12a35180-cef3-11eb-97ce-b1569cae7186.png)

**Comment by grtcdr** [comment] 2021-06-16 20:41
This feature was suggested and discussed many times before, and now might just be the time it makes its appearance.

It is however a duplicate of [#32 in libmacchina](https://github.com/Macchina-CLI/libmacchina/issues/32), so I'll be closing this one and we can discuss this feature over there :)

**Closed** 2021-06-16 20:48 UTC
Labels: enhancement
