### ISSUE TITLE
"Could not locate the configuration file" prints on every run

### ISSUE THREAD

**Issue by 414owen** [Macchina-CLI/macchina#246] opened 2021-12-26 02:05 UTC
This seems to be have been introduced between versions 5.0.5 and 6.0.1.

```
./result/bin/macchina
Error: Custom { kind: NotFound, error: "Could not locate the configuration file" }

        a8888b.           Host        -  owen@nixos
       d888888b.          Machine     -  Dell Inc. XPS 13 9370
 ...
```

I personally didn't plan on writing a macchina config file, but I don't want that to print on every run.

It's not strictly a bug, but I'm not a fan of this default behavior. It says there's an error, yet it continues running just fine. Maybe this should only be printed when running the `doctor` (`-d`)?

Found this change while reviewing [the nixpkgs upgrade pr](https://github.com/NixOS/nixpkgs/pull/152127)

**Comment by grtcdr** [comment] 2021-12-26 02:18
We're tackling this in `v6.0.2`.

I'm closing this as it's a duplicate of #242

**Closed by grtcdr** 2021-12-26 02:18 UTC

**Comment by grtcdr** [comment] 2022-01-02 16:43
@414owen Is this still an issue with v6.0.2?
