### ISSUE TITLE
[BUG] Macchina panicks due to index out of bounds

### ISSUE THREAD

**Issue by jjvdhoven** [Macchina-CLI/macchina#131] opened 2021-08-18 12:26 UTC
**Describe the bug**
Running `machina` causes a panick in thread 'main' due to 'index out of bounds: the len is 25000 but the index is 25026' on version 0.9.2.

**To Reproduce**
1. Install latest version of macchina via `cargo install macchina`
2. run `macchina` to get a readout of the system and the panick will occur

**Expected behavior**
Rather than showing the system readout the program panicks and doesn't return the system stats.

**Screenshots**
Running machina by itself:
![image](https://user-images.githubusercontent.com/22278716/129896389-04d70a3b-fc45-418b-b5b1-6903d669e32b.png)

Running macchina with RUST_BACKTRACE=1:
![image](https://user-images.githubusercontent.com/22278716/129896314-05d86386-2c4d-4ee1-8e81-1b7ae084c9f1.png)

Running macchina with RUST_BACKTRACE=full:
![image](https://user-images.githubusercontent.com/22278716/129896485-45ba9d4c-0d5e-470c-9789-28a950c2c78b.png)

**`macchina --doctor` output**
Macchina is run on a desktop so the battery cannot be found, this wasn't an issue before so I don't think it's the root cause here. 
![image](https://user-images.githubusercontent.com/22278716/129896637-f5851a1a-3b23-4790-aa60-00e59b025869.png)

**System Information**
 - Distribution: Fedora 34 - kernel 5.13.10
 - Desktop Environment GNOME 40.3.0
 - Operating System Linux
 - Terminal Tillix
 - Macchina's version 0.9.2

**Comment by grtcdr** [comment] 2021-08-18 17:36
I couldn't reproduce the issue, but I believe it is related to rendering. Can you try a different terminal?

**Comment by jjvdhoven** [comment] 2021-08-18 18:08
I've tried Alacritty, Kitty, "Terminal" from GNOME, and Tillix and they all produce a panic with the same exact same amounts for the index and offset. I've tried running GNOME through X instead of Wayland and the issue persists. 

If I run macchina with `--no-ascii` the index goes from 25026 to 25004. adding `--no-box` to this brings it down to 25002. I wasn't able to get this any down further with other `--no-*` flags from `machine --help` to test whether it would not panic if limited enough in its output.

**Comment by grtcdr** [comment] 2021-08-18 21:38
Well that's no good...

Does the issue persist in the latest version of macchina?

**Comment by jjvdhoven** [comment] 2021-08-19 12:02
Yes, the issue sadly persists in v1.0.0. I tried v0.9.2 on another Fedora 34 machine and the panic didn't occur on that machine. The only real difference between the two is that one runs an AMD processor (desktop with panic) and the other an Intel processor. 

I tried older versions of macchina as well since it worked in the past. The last version that I can run without a panic is 0.8.21. Any release after that results in the aforementioned panic with a similar index of 25026. Something between 0.8.21, 0.9.x, and 1.x changed even though they appear to use the same version of tui (0.14.0).

**Comment by 123marvin123** [comment] 2021-08-19 12:51
I can't reproduce the issue. Can you build the macchina executable with the "--debug" flag so we can get more information via the stack trace?

**Comment by jjvdhoven** [comment] 2021-08-19 14:13
Having built macchina with debug info returned the following:

- RUST_BACKTRACE=1
```
macchina git/main*  
❯ RUST_BACKTRACE=1 ./target/debug/macchina
thread 'main' panicked at 'Trying to access position outside the buffer: x=26, y=50, area=Rect { x: 0, y: 0, width: 500, height: 50 }', /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: tui::buffer::Buffer::index_of
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
   3: tui::buffer::Buffer::get_mut
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:184:17
   4: tui::buffer::Buffer::set_style
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:358:17
   5: <tui::widgets::paragraph::Paragraph as tui::widgets::Widget>::render
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/widgets/paragraph.rs:137:9
   6: <macchina::widgets::readout::ReadoutList as tui::widgets::Widget>::render
             at ./src/widgets/readout.rs:123:13
   7: macchina::draw_readout_data
             at ./src/main.rs:108:5
   8: macchina::main
             at ./src/main.rs:394:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

- RUST_BACKTRACE=full
```
macchina git/main*  
❯ RUST_BACKTRACE=full ./target/debug/macchina
thread 'main' panicked at 'Trying to access position outside the buffer: x=26, y=50, area=Rect { x: 0, y: 0, width: 500, height: 50 }', /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
stack backtrace:
   0:     0x55e6fe318890 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e6fe318890 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e6fe318890 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e6fe318890 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e6fe33e14c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55e6fe312bd5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55e6fe31a82b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e6fe31a82b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e6fe31a82b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55e6fe31a301 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55e6fe31aef4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55e6fe31a9d7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x55e6fe318d8c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55e6fe31a939 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55e6fe10052b - std::panicking::begin_panic_fmt::h5479575e112541f8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:     0x55e6fe24f903 - tui::buffer::Buffer::index_of::hed6137b8d33fa782
                               at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
  16:     0x55e6fe24f7da - tui::buffer::Buffer::get_mut::hb6864282fad0a131
                               at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:184:17
  17:     0x55e6fe24fdca - tui::buffer::Buffer::set_style::he6cb903179efe04f
                               at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:358:17
  18:     0x55e6fe24d36f - <tui::widgets::paragraph::Paragraph as tui::widgets::Widget>::render::h81b6289bf0463c79
                               at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/widgets/paragraph.rs:137:9
  19:     0x55e6fe12ec4b - <macchina::widgets::readout::ReadoutList as tui::widgets::Widget>::render::h388bbe9b39ec5c7e
                               at /home/jasper/Projects/macchina/src/widgets/readout.rs:123:13
  20:     0x55e6fe13ab40 - macchina::draw_readout_data::hdf3f5207ae77573c
                               at /home/jasper/Projects/macchina/src/main.rs:108:5
  21:     0x55e6fe13c6de - macchina::main::ha4fbfb9b37954a62
                               at /home/jasper/Projects/macchina/src/main.rs:394:5
  22:     0x55e6fe11fd63 - core::ops::function::FnOnce::call_once::h6703f455f3cb196d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  23:     0x55e6fe11fd39 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf689f8e107bb79fd
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  24:     0x55e6fe1312a9 - std::rt::lang_start::{{closure}}::he409b4998f876f12
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
  25:     0x55e6fe31b3f9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  26:     0x55e6fe31b3f9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  27:     0x55e6fe31b3f9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  28:     0x55e6fe31b3f9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  29:     0x55e6fe31b3f9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  30:     0x55e6fe13129b - std::rt::lang_start::h1b6ffaedbf486d2e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
  31:     0x55e6fe13ccc9 - main
  32:     0x7fc6ccaafb75 - __libc_start_main
  33:     0x55e6fe10193e - _start
  34:                0x0 - <unknown>
```

If there's anything else I can do let me know and I'll try my best to provide it to you.

**Comment by 123marvin123** [comment] 2021-08-19 14:20
Looks like the fixed buffer is overflowing, are you showing a lot of readouts? Can you try to execute this command?

`macchina --show-only LocalIP`

**Comment by jjvdhoven** [comment] 2021-08-19 14:40
By default I think I tried to list everything: host, machine name, kernel, distro, de, wm, packages, local ip, terminal, shell, uptime, cpu, cpu%, and memory. This worked in 0.8.21 and seems to break after that. 

I think I have found the flag that causes the crash. If I enable all options but Resolution it will work just fine, if I enable Resolution it will crash no matter what other `--show-only` flags I have set. I have two monitors connected to this desktop, one 1080p monitor and a 1440p monitor for your information. 

- Stack trace with resolution flag only enable in command `./target/debug/macchina --show-only Resolution`
```
macchina git/main*  
❯ RUST_BACKTRACE=1 ./target/debug/macchina --show-only Resolution
thread 'main' panicked at 'Trying to access position outside the buffer: x=16, y=50, area=Rect { x: 0, y: 0, width: 500, height: 50 }', /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: tui::buffer::Buffer::index_of
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:217:9
   3: tui::buffer::Buffer::get_mut
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:184:17
   4: tui::buffer::Buffer::set_style
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/buffer.rs:358:17
   5: <tui::widgets::paragraph::Paragraph as tui::widgets::Widget>::render
             at /home/jasper/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/widgets/paragraph.rs:137:9
   6: <macchina::widgets::readout::ReadoutList as tui::widgets::Widget>::render
             at ./src/widgets/readout.rs:123:13
   7: macchina::draw_readout_data
             at ./src/main.rs:108:5
   8: macchina::main
             at ./src/main.rs:394:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running any `--show-only` command besides Resulotion returns the expected output and doesn't panic:
![image](https://user-images.githubusercontent.com/22278716/130086870-34e66c79-cc66-4d36-8923-28b7bfa68801.png)

**Comment by jjvdhoven** [comment] 2021-08-19 14:49
If I unplug one of the two monitors it seems to not crash anymore and dumps all the available resolutions that the display can handle:
![image](https://user-images.githubusercontent.com/22278716/130090083-9affd59a-1c6c-4eb2-bd8f-d5ab99b08be7.png)

My guess is that either something goes wrong with non-matching resolutions across different screens or multiple monitors in general with the Resolution flag enabled.

**Comment by 123marvin123** [comment] 2021-08-19 14:54
Looks like a readout issue which causes the buffer to overflow because too many lines are printed. This must be fixed in libmacchina @grtcdr

**Comment by grtcdr** [comment] 2021-08-19 15:59
I'll look into this. 

Resolution at the moment can be fetched in one of two ways: through X11, or through `/sys/class/drm`. I'm not sure which one is producing the bug.

**Comment by grtcdr** [comment] 2021-08-19 16:11
This actually might be `/sys/class/drm` causing the issue, because resolutions are newline separated in `modes` file.

**Comment by grtcdr** [comment] 2021-08-19 21:23
@jjvdhoven can you try building macchina from the above mentioned pull request and see if that fixes the issue?

**Comment by jjvdhoven** [comment] 2021-08-19 22:30
@grtcdr With the changes from the PR it now shows the correct resolutions for both monitors and no longer panics! The only change I would perhaps request is to remove the trailing comma from the last resolution displayed. 

![image](https://user-images.githubusercontent.com/22278716/130152427-71b5d775-b3c1-4172-9026-c9032744b605.png)

**Comment by grtcdr** [comment] 2021-08-19 22:30
Will do! Thank you for helping out :)

**Comment by grtcdr** [comment] 2021-08-19 22:31
I'm also noticing the last characters of a particular resolution are being deleted. I'll fix that right away.

**Comment by grtcdr** [comment] 2021-08-19 22:56
It should be fixed now.

**Comment by jjvdhoven** [comment] 2021-08-19 23:02
Yes, it works flawlessly now. Glad I could assist in fixing this!

**Closed** 2021-08-19 23:17 UTC
Labels: bug

**Comment by grtcdr** [comment] 2021-08-19 23:18
Awesome, I've merged the PR. The next release will feature these fixes.
