### ISSUE TITLE
Inaccurate number of installed Cargo packages

### ISSUE THREAD

**Issue by nth10sd** [Macchina-CLI/macchina#327] opened 2024-09-13 21:26 UTC
**Describe the bug**
I run `cargo install --list | rg " v" | wc -l` to get the number of cargo packages installed, and this is accurate when I count manually. `neowofetch` (via `hyfetch`) is also accurate, but macchina gets it incorrect.

**To Reproduce**
1. Install Rust, and then some packages via Cargo
2. Run macchina

**Expected behavior**
The correct number of packages should appear

**`macchina --doctor` output**
N.A., the element is showing up but with the wrong value.

**System Information**
 - Distribution: Tested on Gentoo and Ubuntu
 - Desktop Environment: WSL
 - Macchina's version:

```
$ macchina  --version
macchina     6.2.1
libmacchina  7.3.1
```

**Comment by grtcdr** [comment] 2024-09-13 22:21
I can't reproduce this.

```
Packages    -  784 (pacman), 2 (cargo) 
```

```
~ $ ls ~/.local/share/cargo/bin
macchina  paspio
```

I also doubt we're doing it wrong, our formula for counting your cargo packages is really, really simple.

``` rust
let bin = home::cargo_home().ok()?.join("bin");
let read_dir = read_dir(bin).ok()?;

match read_dir.count() {
   0 => None,
   pkgs => Some(pkgs),
}
```

**Comment by nth10sd** [comment] 2024-09-13 23:07
Oh, you're counting the number of binaries installed in the `bin/` folder of cargo's home.

I was using `cargo install --list | rg " v" | wc -l` to count the number of manually installed packages, and it seems some default binaries are excluded, but included in your method.

```
$ ls ~/.cargo/bin
bat             cargo-clippy          cargo-install-update-config  cargo-udeps    cw     fd    imgcatr   pfetch  rust-analyzer  rustfmt      rust-lldb  srgn   tre
cargo           cargo-fmt             cargo-miri                   cbindgen       difft  fnm   macchina  procs   rustc          rust-gdb     rustup     tldr   tuc
cargo-binstall  cargo-install-update  cargo-tarpaulin              clippy-driver  dua    grex  mdcat     rls     rustdoc        rust-gdbgui  sd         tokei
```

```
$ ls ~/.local/share/bin
$
```

```
$ cargo install --list | rg " v"
bat v0.24.0:
cargo-binstall v1.7.3:
cargo-tarpaulin v0.30.0:
cargo-udeps v0.1.48:
cargo-update v13.4.0:
cbindgen v0.26.0:
cw v0.7.0:
difftastic v0.58.0:
dua-cli v2.29.0:
fd-find v10.1.0:
fnm v1.37.1:
grex v1.4.5:
imgcatr v0.1.4:
macchina v6.2.1:
mdcat v2.1.2:
pfetch v2.11.0:
procs v0.14.5:
sd v1.0.0:
srgn v0.12.0:
tealdeer v1.6.1:
tokei v12.1.2:
tre v0.1.1:
tuc v1.2.0:
```

FWIW, I used Rust's official method of installation as per their website:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by grtcdr** [comment] 2024-09-14 00:12
It seems that cargo is counting packages that aren't there, for example, running `cargo install --list` returns the following:

```
cross v0.2.5:
    cross
    cross-util
macchina v6.2.1 (/home/grtcdr/projects/macchina):
    macchina
paspio v1.0.0:
    paspio
```

But cross is not installed on my machine (running it yields "command not found: cross") and the binary does not exist under cargo's `bin` directory, this leads me to believe cargo has its own cache of sorts and relying on regular expressions as a method of counting currently installed packages could be misrepresentative of the available packages. Either that or I'm something more subtle is going on.

**Comment by grtcdr** [comment] 2024-09-14 00:42
I installed a few packages, macchina included, within a container using the `docker.io/rust` image. `/usr/local/cargo/bin` was pre-populated with some Rust- and Cargo-specific tools, I installed `cross`, ran `macchina` to see the count and immediately uninstalled it to see the new count, it was correct. I'm not sure what's interfering with our local setups.

**Comment by grtcdr** [comment] 2024-10-06 00:05
I'm closing this issue as it hasn't seen much activity and also because it's difficult to reproduce.

**Closed by grtcdr** 2024-10-06 00:05 UTC
