### ISSUE TITLE
[BUG] version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by changbowen** [Macchina-CLI/macchina#305] opened 2024-03-15 12:29 UTC
**Describe the bug**
Getting these when executing the binaries downloaded from release page:
```
./macchina-linux-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./macchina-linux-x86_64)
./macchina-linux-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./macchina-linux-x86_64)
./macchina-linux-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./macchina-linux-x86_64)
```

The host machine is a Proxmox PVE 7.4-17.
Kernel version `Linux 5.15.143-1-pve #1 SMP PVE 5.15.143-1 (2024-02-08T18:12Z)`.

The same binary runs fine in for example WSL.

**To Reproduce**
1. Download https://github.com/Macchina-CLI/macchina/releases/download/v6.1.8/macchina-linux-x86_64 and save to pve host.
2. Login to root@pvehost, locate the binary and run `./macchina-linux-x86_64`.
3. The error above is displayed.

**`macchina --doctor` output**
Same error.

**Comment by Gobidev** [comment] 2024-03-15 12:55
You need to install `glibc` to run the binary built for `x86_64-unknown-linux-gnu`.
On Proxmox, you should be able to install the `build-essential` package with `apt install build-essential`.

**Comment by changbowen** [comment] 2024-03-15 16:07
I was hoping I could use it without having to install anything on the host OS since it is not really a "client"..
Anyway thanks for the information!

**Comment by Gobidev** [comment] 2024-03-15 19:53
You can also avoid installing `glibc` by using a `macchina` binary built for `x86_64-unknown-linux-musl`. This is not available in the Github release, but you could compile `macchina` yourself for that target and use that binary.

**Comment by grtcdr** [comment] 2024-03-17 16:15
I see @Gobidev has already presented two decent solutions. I'll close this issue because it's not a bug.

**Closed by grtcdr** 2024-03-17 16:15 UTC

**Comment by changbowen** [comment] 2024-03-18 14:16
Just want to share that I managed to build the binary for `x86_64-unknown-linux-musl` and it worked :)
Here is the built binary based on v6.1.8 in case anyone needs it: [macchina-unknown-linux-musl-x86_64.zip](https://github.com/Macchina-CLI/macchina/files/14637534/macchina-unknown-linux-musl-x86_64.zip)
